name: Bump micromamba version
on:
  workflow_dispatch:
  schedule:
    # every day at 6am
    - cron: "0 6 * * *"

jobs:
  bump-micromamba:
    strategy:
      matrix:
        include:
          # - name: wiiu-cemu
          #   type: cask
          - name: ryujinx-ava
            type: cask
          - name: upscayl
            type: cask
          # - name: cythonbuilder
          #   type: formula
          # - name: pixi
          #   type: formula
    name: Bump ${{ matrix.name }}
    runs-on: macos-latest
    steps:
      - run: brew tap pavelzw/pavelzw
      - run: |
            echo outdated="$(brew livecheck pavelzw/pavelzw/${{ matrix.name }} --json | jq '.[0].version.outdated')" >> $GITHUB_OUTPUT
            echo new-version="$(brew livecheck pavelzw/pavelzw/${{ matrix.name }} --json | jq '.[0].version.latest')" >> $GITHUB_OUTPUT
        id: livecheck
        shell: bash -eo pipefail {0}
      - name: brew bump-${{ matrix.type }}-pr ${{ matrix.name }}
        run: |
          brew bump-${{ matrix.type }}-pr pavelzw/pavelzw/${{ matrix.name }} --version=${{ steps.livecheck.outputs.new-version }} --no-browse --write-only
        if: steps.livecheck.outputs.outdated == true
      - name: Create Pull Request
        if: steps.livecheck.outputs.outdated == true
        uses: peter-evans/create-pull-request@v5
        with:
          title: ${{ matrix.name }} ${{ steps.livecheck.outputs.new-version }}
          delete-branch: true
